name: Release Rulesfile

on:
  - push

jobs:
  Release-Rulesfile:

    runs-on: ubuntu-latest

    steps:

      - name: Download falcoctl
        run:  wget https://github.com/falcosecurity/falcoctl/releases/download/v0.4.0/falcoctl_0.4.0_linux_amd64.tar.gz

      - name: Extract falcoctl
        run:  tar xvf falcoctl_0.4.0_linux_amd64.tar.gz

      - name: Checkout Rules
        uses: actions/checkout@v3

      - name: Get lowercase OCI repo prefix
        run: |
          echo "OCI_REPO_PREFIX=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Upload OCI artifacts to GitHub packages
        env:
          REGISTRY_USER: ${{ github.repository_owner }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git

        run: printf "Registry User: %s\nRegistry Token: %s\nGitHub_Repo_URL: %s\nOCI Repo Prefix: %s\n" \
                    ${REGISTRY_USER} ${REGISTRY_TOKEN} ${GITHUB_REPO_URL} ${OCI_REPO_PREFIX}
